name: PHP-Unit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8'
        extensions: xml
        coverage: xdebug
        tools: phpunit, psalm

    - name: Install Composer dependencies
      run: |
        make install

    - name: Run unit tests
      run: |
        make test_unit

    - name: Run Psalm
      run: make test_psalm

    - name: Run sniffer
      run: make test_sniff
